FROM kong:0.14.1-centos

MAINTAINER byrd kuangxiaopeng@thundersdata.com

RUN yum -y update && yum -y install unzip openssl-devel

ADD load_kong_conf.sh /etc/kong

CMD luarocks install kong-plugin-td-kong-plugin; \
    kong start

ADD patches/openresty/lua-resty-string/aes.lua /usr/local/openresty/lualib/resty/aes.lua 


